version: '3'

services:
  test-postgres:
    image: postgres
    environment:
      POSTGRES_PASSWORD: "postgres"
    ports:
      - "5432:5432"
    volumes:
      - /home/alessandro/.postgres:/var/lib/postgresql/data
    networks:
      - postgres-compose-network
  
  test-pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: "postgres@postgresql.org"
      PGADMIN_DEFAULT_PASSWORD: "postgres"
    ports:
      - "15432:80"
    depends_on:
      - test-postgres
    networks:
      - postgres-compose-network

  test-pgweb:
    image: sosedoff/pgweb
    environment:
      DATABASE_URL: postgres://postgres:postgres@test-postgres:5432/postgres?sslmode=disable
    ports:
      - "8081:8081"
    depends_on:
      - test-postgres
    networks:
      - postgres-compose-network

networks:
  postgres-compose-network:
    driver: bridge
